log:
  level: info

oss:
  endpoint: oss-cn-hongkong.aliyuncs.com
  bucket: summation-datapool
  prefix: dev

tracing:
  console: false
  request: true
  resp: true
  # Included:
  # -
  excluded:
    - /healthz

  loki:
    URL: http://192.168.176.87:3100